### PR TITLE
Refactoring and tests

### PR DESCRIPTION
**Pull request by KostyaEsmukov**
## DO NOT MERGE THIS - WORK IN PROGRESS

Here we go.

I suggest to review commit-by-commit rather than the resulting changeset.

Feel free to leave comments here. The earlier you notice something - the less bad will be done :)

### CODE REVIEW

**Comment by flongo82** [comment]
Commit 6216872 can be merged for sure.

**Comment by flongo82** [comment]
I would like to understand better commit 8f46fa6. I do not know mocha and instanbul. Could you elaborate a little bit what they are used for?

**Comment by KostyaEsmukov** [comment]
Sure.

Mocha - is one of the strongest testing framework in nodejs world. It's purpose is to run tests like this one: https://mochajs.org/#getting-started .

Istanbul - is a tool to compute the percentage of the source code covered by tests. 
See: https://www.npmjs.com/package/istanbul 
Here is a sample report, generated by it: http://gotwarlost.github.io/istanbul/public/coverage/lcov-report/index.html 

Also please consider using https://travis-ci.org/ . This is not something urgent and really important, but still. 
Here is a sample travis report: https://travis-ci.org/expressjs/express

**Comment by KostyaEsmukov** [comment]
Huge commit in here! Feel free to explore it 😊

**Comment by KostyaEsmukov** [comment]
Folks, do you track it? It would be nice to hear a word or two from you 😄

**Comment by gmerlino** [comment]
Thanks Kostya, we just merged your PR cleanly, from the command line, to another branch we created. I'll leave the PR open on GitHub just to (informally) track the status of our merging to master, and any questions we may have about your commits in the meantime.

**Comment by KostyaEsmukov** [comment]
Sweet! But please keep in mind that it's not over yet. Plugins, drivers and socat parts are not integrated yet. I hope to complete it by Wednesday, including running on a real device. I will surely leave a note here when I'm done. 

Also, please make sure that you are comfortable working with that code. It's way more modular and abstractional than before.

**Pull request closed without merging**
